name: CycloneDX SBOM Open Source Vulnerabilities Report Action
description: Create a CSV report for all true positive vulnerabilities for a project based on it's CycloneDX SBOM
author: sean.smith [B00158319@mytudublin.ie]

inputs:
  github-server-url:
    description: URL of the GitHub server
    type: string
    required: false
    default: ${{ github.server_url }}

  github-api-url:
    description: URL of the GitHub API
    type: string
    required: false
    default: ${{ github.api_url }}

  github-api-token:
    description: Token to access the GitHub API
    type: string
    required: true

  experiment-id:
    description: Experiment ID to record in the report
    type: string
    required: true

  experiment-github-project-name:
    description: Name of the experiment GitHub project
    type: string
    required: true

  experiment-github-repository:
    description: Name of the experiment GitHub repository
    type: string
    required: false
    default: ${{ github.repository }}

  experiment-github-branch:
    description: Name of the experiment GitHub branch
    type: string
    required: false
    default: ${{ github.ref_name }}

  experiment-github-commit:
    description: SHA of the experiment GitHub commit
    type: string
    required: false
    default: ${{ github.sha }}

  experiment-github-workflow-name:
    description: Name of the experiment GitHub workflow
    type: string
    required: false
    default: ${{ github.workflow }}

  experiment-github-workflow-run-id:
    description: ID of the experiment GitHub workflow run
    type: string
    required: false
    default: ${{ github.run_id }}

  experiment-runner-environment:
    description: Environment of the GitHub runner
    type: string
    required: false
    default: ${{ runner.environment }}

  experiment-runner-operating-system:
    description: Operating system of the GitHub runner
    type: string
    required: false
    default: ${{ runner.os }}

  experiment-runner-architecture:
    description: Architecture of the GitHub runner
    type: string
    required: false
    default: ${{ runner.arch }}

  experiment-programming-language:
    description: Programming language of the experiment
    type: string
    required: true

  cyclonedx-sbom-filename:
    description: Name of CycloneDX SBOM filename
    type: string
    required: true

  csv-report-filename:
    description: Name of the CSV report filename
    type: string
    required: false
    default: cyclonedx_sbom_osv_report.csv

  artifact-name:
    description: Name of the artifact to upload
    type: string
    required: false
    default: cyclonedx-sbom-osv-report

  path:
    description: Directory to run the action
    type: string
    required: false

  include-unit-tests:
    description: Run unit tests in the action (for testing use only)
    type: string # See https://github.com/actions/runner/issues/2238
    required: false
    default: false

runs:
    using: composite
    steps:
      - name: Install Python 3.12
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12

      - name: Install Python Dependencies
        shell: bash
        working-directory: ${{ github.action_path }}
        run: pip install -r requirements-dev.txt

      - name: Run Unit Tests
        if: ${{ inputs.include-unit-tests == 'true' && runner.os != 'Windows' }}
        shell: bash
        working-directory: ${{ github.action_path }}
        run: ./run_unit_tests.sh

      - name: Create CycloneDX SBOM OSV Report
        shell: bash
        working-directory: ${{ github.action_path }}
        run: >
          python src/main/python3/cyclonedx_sbom_osv_report.py
          --github-server-url ${{ inputs.github-server-url }}
          --github-api-url ${{ inputs.github-api-url }}
          --github-api-token ${{ inputs.github-api-token }}
          --experiment-id ${{ inputs.experiment-id }}
          --experiment-github-project-name "${{ inputs.experiment-github-project-name }}"
          --experiment-github-repository ${{ inputs.experiment-github-repository }}
          --experiment-github-branch ${{ inputs.experiment-github-branch }}
          --experiment-github-commit ${{ inputs.experiment-github-commit }}
          --experiment-github-workflow-name "${{ inputs.experiment-github-workflow-name }}"
          --experiment-github-workflow-run-id ${{ inputs.experiment-github-workflow-run-id }}
          --experiment-runner-environment ${{ inputs.experiment-runner-environment }}
          --experiment-runner-operating-system ${{ inputs.experiment-runner-operating-system }}
          --experiment-runner-architecture ${{ inputs.experiment-runner-architecture }}
          --experiment-programming-language ${{ inputs.experiment-programming-language }}
          --cyclonedx-sbom-filename ${{ inputs.cyclonedx-sbom-filename }}
          --csv-report-filename ${{ inputs.csv-report-filename }}

      # See https://github.com/actions/runner/issues/2185
      # For Windows - github.action_path uses backslashes but path arg only accepts forward slashes
      - name: Set GitHub Action Path
        shell: bash
        run: |
          if [[ "${{ inputs.experiment-runner-operating-system }}" == "Linux" || "${{ inputs.experiment-runner-operating-system }}" == "macOS" ]]; then
              GITHUB_ACTION_NEW_PATH=$(python -c "print('${{ github.action_path }}'.replace('./', ''))")
          else
              GITHUB_ACTION_NEW_PATH="${{ inputs.path }}/.github/actions/reporting/cyclonedx-sbom-osv-report"
          fi
          echo "GITHUB_ACTION_NEW_PATH=$GITHUB_ACTION_NEW_PATH" >> $GITHUB_ENV

      - name: Upload CycloneDX SBOM OSV Report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: "${{ env.GITHUB_ACTION_NEW_PATH }}/src/main/python3/${{ inputs.csv-report-filename }}"
          if-no-files-found: error
