name: Test Java Dependency Tree Action

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  test-action:
    name: Test Java Dependency Tree Action
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
        category: [
          { repository: seansmith2600/H6060-Java-Logback, ref: 7ee000a0a359d239c60bb93a2f4f4ea467c38395 },
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Upstream Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.category.repository }}
          ref: ${{ matrix.category.ref }}
          path: upstream-repository

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Create Java Dependency Tree
        uses: ./experiment-resources/.github/actions/java/java-dependency-tree
        with:
          artifact-name: java-dependency-tree-${{ matrix.os }}
          path: upstream-repository
