name: Test Python Dependency Tree Action

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  test-action-job:
    name: Test Python Dependency Tree Action
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
        category: [
          { repository: seansmith2600/H6060-Python-Urllib3, ref: d1616473df94b94f0f5ad19d2a6608cfe93b7cdf },
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Upstream Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.category.repository }}
          ref: ${{ matrix.category.ref }}
          path: upstream-repository

      # Python version < 3.8 no longer supported on MacOS
      # See issue: https://github.com/actions/runner-images/issues/9770#issuecomment-2085623315
      - name: Install Python 3.8
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        working-directory: upstream-repository
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools build wheel nox

      - name: Create Python Dependency Tree
        uses: ./experiment-resources/.github/actions/python/python-dependency-tree
        with:
          artifact-name: python-dependency-tree-${{ matrix.os }}
          path: upstream-repository
