name: Test OpenTelemetry Metrics Exporter Action

on:
  workflow_dispatch:

permissions:
  security-events: write

defaults:
  run:
    shell: bash

jobs:
  compile-job:
    name: Compile
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        category: [
          { repository: seansmith2600/H6060-JavaScript-Lodash, ref: 1144918f3578a84fcc4986da9b806e63a6175cbb },
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Upstream Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.category.repository }}
          ref: ${{ matrix.category.ref }}
          path: upstream-repository

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x

      - name: Install JavaScript Dependencies
        working-directory: upstream-repository
        run: npm ci

  test-action:
    name: Test OpenTelemetry Metrics Exporter Action
    needs: compile-job
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Send GitHub Workflow Metrics To OpenTelemetry
        uses: ./experiment-resources/.github/actions/metrics/opentelemetry-metrics-exporter
        with:
          honeycomb-api-key: ${{ secrets.TEST_HONEYCOMB_API_KEY }}
          original-github-workflow-name: ${{ github.workflow }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
