name: Test Eclipse Steady SCA Action

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  test-action-java:
    name: Test Eclipse Steady SCA Action (Java)
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        category: [
          { repository: seansmith2600/H6060-Java-Logback, ref: 7ee000a0a359d239c60bb93a2f4f4ea467c38395, programming-language: java }
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Upstream Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.category.repository }}
          ref: ${{ matrix.category.ref }}
          path: upstream-repository

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Build Java Application
        uses: ./experiment-resources/.github/actions/java/java-build
        with:
          build-command: mvn -Dmaven.test.skip=true clean install
          build-directory: "**/target"
          artifact-name: java-build-${{ matrix.os }}
          path: upstream-repository

      - name: Run Eclipse Steady (SCA)
        uses: ./experiment-resources/.github/actions/sca/eclipse-steady/java
        with:
          build-directory: target
          eclipse-steady-workspace-token: BAB77AC201B415E4F2D8F32CE2286B15
          eclipse-steady-backend-url: http://steady-ubuntu.b00158319.com:8033/backend
          eclipse-steady-cia-url: http://steady-ubuntu.b00158319.com:8033/cia
          eclipse-steady-application-group-id: ch.qos.logback
          eclipse-steady-application-artifact-id: logback-parent
          eclipse-steady-application-version: 1.4.13
          eclipse-steady-project-source-directories: logback-access/src,logback-classic/src,logback-core/src,logback-examples/src
          artifact-name: sast-eclipse-steady-report-${{ matrix.category.programming-language }}-${{ matrix.os }}
          path: upstream-repository

  test-action-python:
    name: Test Eclipse Steady SCA Action (Python)
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        category: [
          { repository: seansmith2600/H6060-Python-Urllib3, ref: d1616473df94b94f0f5ad19d2a6608cfe93b7cdf, programming-language: python }
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: experiment-resources

      - name: Checkout Upstream Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.category.repository }}
          ref: ${{ matrix.category.ref }}
          path: upstream-repository

      # Python version < 3.8 no longer supported on MacOS
      # See issue: https://github.com/actions/runner-images/issues/9770#issuecomment-2085623315
      - name: Install Python 3.8
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        working-directory: upstream-repository
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools build wheel nox

      - name: Build Python Application
        uses: ./experiment-resources/.github/actions/python/python-build
        with:
          build-command: python -m build
          build-directory: dist
          artifact-name: python-build-${{ matrix.os }}
          path: upstream-repository

      - name: Run Eclipse Steady (SCA)
        uses: ./experiment-resources/.github/actions/sca/eclipse-steady/python
        with:
          eclipse-steady-workspace-token: B980175C6DAEEFDA6016E9B8789DADC3
          eclipse-steady-backend-url: http://steady-ubuntu.b00158319.com:8033/backend
          eclipse-steady-application-group-id: org.python
          eclipse-steady-application-artifact-id: urllib3
          eclipse-steady-application-version: 1.26.5
          eclipse-steady-project-source-directories: src
          artifact-name: sca-eclipse-steady-report-${{ matrix.category.programming-language }}-${{ matrix.os }}
          path: upstream-repository
